package com.contest.parking.domain;

import com.contest.parking.data.model.Storico;
import com.contest.parking.data.repository.PostoAutoRepository;
import com.contest.parking.data.repository.StoricoRepository;
import com.google.android.gms.tasks.OnSuccessListener;

import java.util.Date;

public class UseCasePrenotaPosto {

    private PostoAutoRepository postoAutoRepository;
    private StoricoRepository storicoRepository;

    public UseCasePrenotaPosto(PostoAutoRepository postoAutoRepository, StoricoRepository storicoRepository) {
        this.postoAutoRepository = postoAutoRepository;
        this.storicoRepository = storicoRepository;
    }

    // Book a parking spot and save the booking in the history
    public void prenotaPosto(String postoId,
                             String utenteId,
                             String targa,
                             double prezzo,
                             OnSuccessListener<Void> onSuccess) {

        // Uppdate PostoAuto statoOccupato
        postoAutoRepository.updateStatoPostoAuto(postoId, true)
                .addOnSuccessListener(aVoid -> {
                    // create a new Storico
                    Storico s = new Storico();
                    s.setId(""); // generated by repository
                    s.setUtenteId(utenteId);
                    s.setPostoAutoId(postoId);
                    s.setTarga(targa);
                    s.setPrezzo(prezzo);
                    s.setDataInizio(new Date().getTime());
                    s.setDataFine(0); // 0 se non definito

                    storicoRepository.addStorico(s)
                            .addOnSuccessListener(onSuccess)
                            .addOnFailureListener(e -> {
                                // in case of error in adding the booking to the history, restore the parking spot
                            });
                })
                .addOnFailureListener(e -> {
                    // TODO handle error
                });
    }
}
